# Generated by Django 4.0.3 on 2022-05-31 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='user',
        ),
    ]
